//
//  CurrencyService.swift
//  CurrencySwift
//
//  Created by Akhmed on 06.06.24.
//

import Foundation
import Combine

class CurrencyService: CurrencyServiceProtocol {
    let apiKey = "8b3be48fdb7337bf7cc4c2dc"
    let baseURL = "https://v6.exchangerate-api.com/v6/"
    
    let countryMapping: [String: String] = [
        "USD": "United States",
        "AED": "United Arab Emirates",
        "AFN": "Afghanistan",
        "ALL": "Albania",
        "AMD": "Armenia",
        "ANG": "Netherlands Antilles",
        "AOA": "Angola",
        "ARS": "Argentina",
        "AUD": "Australia",
        "AWG": "Aruba",
        "AZN": "Azerbaijan",
        "BAM": "Bosnia and Herzegovina",
        "BBD": "Barbados",
        "BDT": "Bangladesh",
        "BGN": "Bulgaria",
        "BHD": "Bahrain",
        "BIF": "Burundi",
        "BMD": "Bermuda",
        "BND": "Brunei",
        "BOB": "Bolivia",
        "BRL": "Brazil",
        "BSD": "Bahamas",
        "BTN": "Bhutan",
        "BWP": "Botswana",
        "BYN": "Belarus",
        "BZD": "Belize",
        "CAD": "Canada",
        "CDF": "Democratic Republic of the Congo",
        "CHF": "Switzerland",
        "CLP": "Chile",
        "CNY": "China",
        "COP": "Colombia",
        "CRC": "Costa Rica",
        "CUP": "Cuba",
        "CVE": "Cape Verde",
        "CZK": "Czech Republic",
        "DJF": "Djibouti",
        "DKK": "Denmark",
        "DOP": "Dominican Republic",
        "DZD": "Algeria",
        "EGP": "Egypt",
        "ERN": "Eritrea",
        "ETB": "Ethiopia",
        "EUR": "Eurozone",
        "FJD": "Fiji",
        "FKP": "Falkland Islands",
        "FOK": "Faroe Islands",
        "GBP": "United Kingdom",
        "GEL": "Georgia",
        "GGP": "Guernsey",
        "GHS": "Ghana",
        "GIP": "Gibraltar",
        "GMD": "Gambia",
        "GNF": "Guinea",
        "GTQ": "Guatemala",
        "GYD": "Guyana",
        "HKD": "Hong Kong",
        "HNL": "Honduras",
        "HRK": "Croatia",
        "HTG": "Haiti",
        "HUF": "Hungary",
        "IDR": "Indonesia",
        "ILS": "Israel",
        "IMP": "Isle of Man",
        "INR": "India",
        "IQD": "Iraq",
        "IRR": "Iran",
        "ISK": "Iceland",
        "JEP": "Jersey",
        "JMD": "Jamaica",
        "JOD": "Jordan",
        "JPY": "Japan",
        "KES": "Kenya",
        "KGS": "Kyrgyzstan",
        "KHR": "Cambodia",
        "KID": "Kiribati",
        "KMF": "Comoros",
        "KRW": "South Korea",
        "KWD": "Kuwait",
        "KYD": "Cayman Islands",
        "KZT": "Kazakhstan",
        "LAK": "Laos",
        "LBP": "Lebanon",
        "LKR": "Sri Lanka",
        "LRD": "Liberia",
        "LSL": "Lesotho",
        "LYD": "Libya",
        "MAD": "Morocco",
        "MDL": "Moldova",
        "MGA": "Madagascar",
        "MKD": "North Macedonia",
        "MMK": "Myanmar",
        "MNT": "Mongolia",
        "MOP": "Macau",
        "MRU": "Mauritania",
        "MUR": "Mauritius",
        "MVR": "Maldives",
        "MWK": "Malawi",
        "MXN": "Mexico",
        "MYR": "Malaysia",
        "MZN": "Mozambique",
        "NAD": "Namibia",
        "NGN": "Nigeria",
        "NIO": "Nicaragua",
        "NOK": "Norway",
        "NPR": "Nepal",
        "NZD": "New Zealand",
        "OMR": "Oman",
        "PAB": "Panama",
        "PEN": "Peru",
        "PGK": "Papua New Guinea",
        "PHP": "Philippines",
        "PKR": "Pakistan",
        "PLN": "Poland",
        "PYG": "Paraguay",
        "QAR": "Qatar",
        "RON": "Romania",
        "RSD": "Serbia",
        "RUB": "Russia",
        "RWF": "Rwanda",
        "SAR": "Saudi Arabia",
        "SBD": "Solomon Islands",
        "SCR": "Seychelles",
        "SDG": "Sudan",
        "SEK": "Sweden",
        "SGD": "Singapore",
        "SHP": "Saint Helena",
        "SLE": "Sierra Leone",
        "SLL": "Sierra Leone",
        "SOS": "Somalia",
        "SRD": "Suriname",
        "SSP": "South Sudan",
        "STN": "Sao Tome and Principe",
        "SYP": "Syria",
        "SZL": "Eswatini",
        "THB": "Thailand",
        "TJS": "Tajikistan",
        "TMT": "Turkmenistan",
        "TND": "Tunisia",
        "TOP": "Tonga",
        "TRY": "Turkey",
        "TTD": "Trinidad and Tobago",
        "TVD": "Tuvalu",
        "TWD": "Taiwan",
        "TZS": "Tanzania",
        "UAH": "Ukraine",
        "UGX": "Uganda",
        "UYU": "Uruguay",
        "UZS": "Uzbekistan",
        "VES": "Venezuela",
        "VND": "Vietnam",
        "VUV": "Vanuatu",
        "WST": "Samoa",
        "XAF": "Central African CFA franc",
        "XCD": "East Caribbean dollar",
        "XDR": "International Monetary Fund",
        "XOF": "West African CFA franc",
        "XPF": "CFP franc",
        "YER": "Yemen",
        "ZAR": "South Africa",
        "ZMW": "Zambia",
        "ZWL": "Zimbabwe"
    ]

    
    func fetchRates(base: String) -> AnyPublisher<CurrencyData, Error> {
        let urlString = "\(baseURL)\(apiKey)/latest/\(base)"
        guard let url = URL(string: urlString) else {
            return Fail(error: URLError(.badURL)).eraseToAnyPublisher()
        }
        
        return URLSession.shared.dataTaskPublisher(for: url)
            .map(\.data)
            .decode(type: CurrencyData.self, decoder: JSONDecoder())
            .mapError { error -> Error in
                return error
            }
            .eraseToAnyPublisher()
    }
}



